#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-keras
Version  : 2.15.0
Release  : 53
URL      : https://cran.r-project.org/src/contrib/keras_2.15.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/keras_2.15.0.tar.gz
Summary  : R Interface to 'Keras'
Group    : Development/Tools
License  : MIT
Requires: R-R6
Requires: R-generics
Requires: R-glue
Requires: R-magrittr
Requires: R-reticulate
Requires: R-rlang
Requires: R-tensorflow
Requires: R-tfruns
Requires: R-zeallot
BuildRequires : R-R6
BuildRequires : R-devtools
BuildRequires : R-generics
BuildRequires : R-glue
BuildRequires : R-magrittr
BuildRequires : R-reticulate
BuildRequires : R-rlang
BuildRequires : R-tensorflow
BuildRequires : R-tfruns
BuildRequires : R-zeallot
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
networks 'API'. 'Keras' was developed with a focus on enabling fast experimentation,
  supports both convolution based networks and recurrent networks (as well as
  combinations of the two), and runs seamlessly on both 'CPU' and 'GPU' devices.

%prep
%setup -q -n keras
pushd ..
cp -a keras buildavx2
popd
pushd ..
cp -a keras buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713670979

%install
export SOURCE_DATE_EPOCH=1713670979
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/keras/DESCRIPTION
/usr/lib64/R/library/keras/INDEX
/usr/lib64/R/library/keras/LICENSE
/usr/lib64/R/library/keras/Meta/Rd.rds
/usr/lib64/R/library/keras/Meta/features.rds
/usr/lib64/R/library/keras/Meta/hsearch.rds
/usr/lib64/R/library/keras/Meta/links.rds
/usr/lib64/R/library/keras/Meta/nsInfo.rds
/usr/lib64/R/library/keras/Meta/package.rds
/usr/lib64/R/library/keras/Meta/vignette.rds
/usr/lib64/R/library/keras/NAMESPACE
/usr/lib64/R/library/keras/NEWS.md
/usr/lib64/R/library/keras/R/keras
/usr/lib64/R/library/keras/R/keras.rdb
/usr/lib64/R/library/keras/R/keras.rdx
/usr/lib64/R/library/keras/doc/applications.R
/usr/lib64/R/library/keras/doc/applications.Rmd
/usr/lib64/R/library/keras/doc/applications.html
/usr/lib64/R/library/keras/doc/custom_layers.R
/usr/lib64/R/library/keras/doc/custom_layers.Rmd
/usr/lib64/R/library/keras/doc/custom_layers.html
/usr/lib64/R/library/keras/doc/custom_models.R
/usr/lib64/R/library/keras/doc/custom_models.Rmd
/usr/lib64/R/library/keras/doc/custom_models.html
/usr/lib64/R/library/keras/doc/faq.R
/usr/lib64/R/library/keras/doc/faq.Rmd
/usr/lib64/R/library/keras/doc/faq.html
/usr/lib64/R/library/keras/doc/functional_api.R
/usr/lib64/R/library/keras/doc/functional_api.Rmd
/usr/lib64/R/library/keras/doc/functional_api.html
/usr/lib64/R/library/keras/doc/guide_keras.R
/usr/lib64/R/library/keras/doc/guide_keras.Rmd
/usr/lib64/R/library/keras/doc/guide_keras.html
/usr/lib64/R/library/keras/doc/index.R
/usr/lib64/R/library/keras/doc/index.Rmd
/usr/lib64/R/library/keras/doc/index.html
/usr/lib64/R/library/keras/doc/saving_serializing.R
/usr/lib64/R/library/keras/doc/saving_serializing.Rmd
/usr/lib64/R/library/keras/doc/saving_serializing.html
/usr/lib64/R/library/keras/doc/sequential_model.R
/usr/lib64/R/library/keras/doc/sequential_model.Rmd
/usr/lib64/R/library/keras/doc/sequential_model.html
/usr/lib64/R/library/keras/doc/training_callbacks.R
/usr/lib64/R/library/keras/doc/training_callbacks.Rmd
/usr/lib64/R/library/keras/doc/training_callbacks.html
/usr/lib64/R/library/keras/doc/training_visualization.R
/usr/lib64/R/library/keras/doc/training_visualization.Rmd
/usr/lib64/R/library/keras/doc/training_visualization.html
/usr/lib64/R/library/keras/help/AnIndex
/usr/lib64/R/library/keras/help/aliases.rds
/usr/lib64/R/library/keras/help/keras.rdb
/usr/lib64/R/library/keras/help/keras.rdx
/usr/lib64/R/library/keras/help/paths.rds
/usr/lib64/R/library/keras/html/00Index.html
/usr/lib64/R/library/keras/html/R.css
/usr/lib64/R/library/keras/python/kerastools/__init__.py
/usr/lib64/R/library/keras/python/kerastools/callback.py
/usr/lib64/R/library/keras/python/kerastools/constraint.py
/usr/lib64/R/library/keras/python/kerastools/generator.py
/usr/lib64/R/library/keras/python/kerastools/get_vocabulary.py
/usr/lib64/R/library/keras/python/kerastools/layer.py
/usr/lib64/R/library/keras/python/kerastools/model.py
/usr/lib64/R/library/keras/python/kerastools/progbar.py
/usr/lib64/R/library/keras/python/kerastools/utils.py
/usr/lib64/R/library/keras/python/kerastools/wrapper.py
/usr/lib64/R/library/keras/tests/testthat.R
/usr/lib64/R/library/keras/tests/testthat/digit.jpeg
/usr/lib64/R/library/keras/tests/testthat/digit2.jpeg
/usr/lib64/R/library/keras/tests/testthat/digit_resized.jpeg
/usr/lib64/R/library/keras/tests/testthat/helper-skips.R
/usr/lib64/R/library/keras/tests/testthat/helper-utils.R
/usr/lib64/R/library/keras/tests/testthat/setup.R
/usr/lib64/R/library/keras/tests/testthat/test-Layer.R
/usr/lib64/R/library/keras/tests/testthat/test-activations.R
/usr/lib64/R/library/keras/tests/testthat/test-applications.R
/usr/lib64/R/library/keras/tests/testthat/test-backend.R
/usr/lib64/R/library/keras/tests/testthat/test-callbacks.R
/usr/lib64/R/library/keras/tests/testthat/test-constraints.R
/usr/lib64/R/library/keras/tests/testthat/test-custom-layers.R
/usr/lib64/R/library/keras/tests/testthat/test-custom-models.R
/usr/lib64/R/library/keras/tests/testthat/test-custom_wrappers.R
/usr/lib64/R/library/keras/tests/testthat/test-datasets.R
/usr/lib64/R/library/keras/tests/testthat/test-examples.R
/usr/lib64/R/library/keras/tests/testthat/test-freeze.R
/usr/lib64/R/library/keras/tests/testthat/test-generators.R
/usr/lib64/R/library/keras/tests/testthat/test-history.R
/usr/lib64/R/library/keras/tests/testthat/test-initializers.R
/usr/lib64/R/library/keras/tests/testthat/test-keras-tensor-generics.R
/usr/lib64/R/library/keras/tests/testthat/test-layer-attention.R
/usr/lib64/R/library/keras/tests/testthat/test-layer-methods.R
/usr/lib64/R/library/keras/tests/testthat/test-layer-text_vectorization.R
/usr/lib64/R/library/keras/tests/testthat/test-layers-normalization.R
/usr/lib64/R/library/keras/tests/testthat/test-layers-preprocessing.R
/usr/lib64/R/library/keras/tests/testthat/test-layers.R
/usr/lib64/R/library/keras/tests/testthat/test-losses.R
/usr/lib64/R/library/keras/tests/testthat/test-metrics.R
/usr/lib64/R/library/keras/tests/testthat/test-model-persistence.R
/usr/lib64/R/library/keras/tests/testthat/test-model.R
/usr/lib64/R/library/keras/tests/testthat/test-optimizers.R
/usr/lib64/R/library/keras/tests/testthat/test-preprocessing.R
/usr/lib64/R/library/keras/tests/testthat/test-py-class.R
/usr/lib64/R/library/keras/tests/testthat/test-regularizers.R
/usr/lib64/R/library/keras/tests/testthat/test-rnn-api.R
/usr/lib64/R/library/keras/tests/testthat/test-tfdatasets.R
/usr/lib64/R/library/keras/tests/testthat/test-timeseries.R
/usr/lib64/R/library/keras/tests/testthat/test-utils.R
/usr/lib64/R/library/keras/tests/testthat/test.h5
/usr/lib64/R/library/keras/tests/testthat/train.R
